### ISSUE TITLE
window dependency

### ISSUE THREAD

**Issue by Hosar** [strophe/strophejs#201]
window.Strophe =        o.Strophe;
        ^

ReferenceError: window is not defined

It would be great if strophe could run with node js and webpack.

**Comment by jcbrand** [comment]
Please make a pull request for this.

**Comment by AndrewRayCode** [comment]
The best friends club:
- https://github.com/ccampbell/mousetrap/issues/283
- https://github.com/zeroclipboard/zeroclipboard/issues/568
- https://github.com/thlorenz/brace/issues/30
- https://github.com/strophe/strophejs/issues/201

**Comment by jcbrand** [comment]
@LeartS has made NodeJS compatibility fixes. Will be released soon.

**Comment by dkasak** [comment]
Has this been released? I'm using 1.4.0 and I'm getting an error about `window` not being defined when trying to use `Connection.connect`:

```
/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:1539
    if (level === this.LogLevel.FATAL && _typeof(window.console) === 'object' && typeof window.console.error === 'function') {
                                                 ^

ReferenceError: window is not defined
    at Object.log (/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:1539:50)
    at Object.fatal (/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:1591:10)
    at Object._handleError (/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:1497:15)
    at Connection._changeConnectStatus (/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:3322:19)
    at Connection.connect (/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:2617:12)
    at Object.<anonymous> (/xmpp_test/app.js:57:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

**Comment by LeartS** [comment]
The PR was this one: https://github.com/strophe/strophejs/pull/329 and I think it was released in 1.3.5 , so not sure what happened. Maybe it's a non-nodejs-compatibile code branch that gets executed only in some specific cases, or maybe some new PRs broke the nodejs compatibility.

I haven't been following the project for a while, so I'm not sure of the recent changes.

**Comment by jcbrand** [comment]
@dkasak Can you please check whether this commit fixes the issue? https://github.com/strophe/strophejs/commit/3ad3973a6061ada16c4c056ae35fc3778076115c

**Comment by dkasak** [comment]
Seems the Travis build is failing for some reason? The same thing happens to me when I try to install it locally.

```
src/strophe.js → dist/strophe.umd.js...
[!] (plugin at position 3) SyntaxError: Unexpected token (764:19) in /home/travis/build/strophe/strophejs/src/core.js
src/core.js (764:19)
SyntaxError: Unexpected token (764:19) in /home/travis/build/strophe/strophejs/src/core.js
    at Parser.pp$4.raise (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp$3.parseExprAtom (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:2196:10)
    at Parser.pp$3.parseExprSubscripts (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:1925:19)
    at Parser.pp$3.parseMaybeConditional (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:1954:28)
    at Parser.pp$3.parseMaybeAssign (/home/travis/build/strophe/strophejs/node_modules/acorn/dist/acorn.js:1925:19)

**Comment by jcbrand** [comment]
Oh, I guess we need to add Babel support for optional chaining.

**Comment by dkasak** [comment]
I just did https://github.com/dkasak/strophejs/commit/94076796b93c9d6dca3809a6f48c76a8a7ba919a as a workaround, but I'm encountering further problems:

```
❯ node app.js 
/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:5927
      this.socket = new WebSocket(this._conn.service, "xmpp");
                        ^

ReferenceError: WebSocket is not defined
    at Websocket._connect (/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:5927:25)
    at Connection.connect (/xmpp_test/node_modules/strophe.js/dist/strophe.common.js:2623:19)
    at Object.<anonymous> (/xmpp_test/app.js:57:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Any ideas why WebSocket would be undefined? I have the `ws` package installed.

**Comment by jcbrand** [comment]
@dkasak: I now added support for optional chaining and I believe the `WebSocket` is `undefined` error should now be fixed as well.

Can you please check?

**Comment by dkasak** [comment]
Seems to be working now, thanks a lot!

**Comment by SravanKumarNangunoori** [comment]
Can you publish the package after the roll up

**Comment by SravanKumarNangunoori** [comment]
@jcbrand  we still have window dependencies on the bosh.js
window.sessionstorage,
window.xmlhttprequest

**Comment by jcbrand** [comment]
@SravanKumarNangunoori Please create a new bug report for those dependencies.
