### ISSUE TITLE
React Native Error

### ISSUE THREAD

**Issue by zek** [strophe/strophejs#310]
Trying to use library in my react project but I got no luck. 

Is it possible to make this project run on react native?

~~~
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 539.20 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.3, macOS 10.13, tvOS 11.3, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 9.3/9E145 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
~~~

~~~
error: bundling failed: Error: Unable to resolve module `./sha1` from `/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/strophe.js/strophe.js`: The module `./sha1` could not be found from `/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/strophe.js/strophe.js`. Indeed, none of these files exist:

  * `/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/strophe.js/sha1(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/strophe.js/sha1/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:697)
    at ResolutionRequest.resolveDependency (/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/zack/Desktop/DERS/react/MyNewApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/zack/Desktop/DERS/react/MyNewApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
~~~

**Comment by zek** [comment]
I can use version 1.2.7. But I am getting errors in upper versions. 
I need to use version 1.2.12 at least.

**Comment by zek** [comment]
I reverted the change #200 and 1.2.12 works.

**Comment by zek** [comment]
~~~
    getElement: function(stanza, elName) {
        var el;

        if(typeof stanza.querySelector === 'function') {
            el = stanza.querySelector(elName);
        } else if(typeof stanza.getChild === 'function'){
            el = stanza.getChild(elName);
        } else {
            throw ERR_UNKNOWN_INTERFACE;
        }

        return el ? el : null;
    },
~~~

There is no querySelector or getChild methods in stanza. Is it related to this hack?
~~~
window.DOMParser = require('xmldom').DOMParser;
window.document = new DOMParser().parseFromString("<?xml version='1.0'?>", 'text/xml');
~~~


When I print the stanza to console this is what I get.

<img width="1025" alt="screen shot 2018-10-14 at 23 53 07" src="https://user-images.githubusercontent.com/3463291/46922079-72435380-d00c-11e8-91e1-ca4068affe64.png">

**Comment by jcbrand** [comment]
> Is it possible to make this project run on react native?

I'm quite sure it's possible, but I can't say what exactly needs to be done. I haven't used react native yet.

**Comment by zek** [comment]
Actually it works. I am able to make it run correctly 👍

With the fix I shared works like a charm

**Comment by jcbrand** [comment]
> With the fix I shared works like a charm

What fix is that exactly?
