### ISSUE TITLE
Not working with Node.js

### ISSUE THREAD

**Issue by EliSnow** [strophe/strophejs#368]
Despite some recent PRs it looks like Strophe (as of version 1.4.1) is not working with Node.js.

The following error occurs when calling the `connect` method on a `Connection` object:

```
  ReferenceError: window is not defined
      at Request._newXHR (/REDACTED/node_modules/strophe.js/dist/strophe.common.js:4843:7)
      at new Request (/REDACTED/node_modules/strophe.js/dist/strophe.common.js:4780:21)
      at Bosh._connect (/REDACTED/node_modules/strophe.js/dist/strophe.common.js:4986:27)
      at Connection.connect (/REDACTED/node_modules/strophe.js/dist/strophe.common.js:2628:19)
```

[A comment in another issue](https://github.com/strophe/strophejs/issues/201#issuecomment-723723904) notes there may be window references in other locations as well. This issue is intended to be broad enough to capture this and any other problems preventing Strophe from working in Node.js.

**Comment by herbertgaoo** [comment]
I use `xhr = new plus.net.XMLHttpRequest();`  to replace the original code and it works, `plus.net` is from Html5+ SDK

**Comment by jcbrand** [comment]
I've recently added tests to run Strophe in Node.js and fixed various issues, including `window` being used.

Should be released soon.
